server:
  port: 8080

#datasource
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/account?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    druid:
    #初始化大小
    initialSize: 5
    #最小值
    minIdle: 5
    #最大值
    maxActive: 20
    #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true


mybatis:
  # model的包
  type-aliases-package: com.banner.sercurity
  configuration:
    # 开启驼峰uName自动映射到u_name
    map-underscore-to-camel-case: true

#打印sql
logging:
  level:
    ssm.app.mapper: debug
#
#jwt:
#  tokenHeader: Authorization
#  tokenPrefix: Bearer
#  secret: lanjwt
#  expiration: 3600
#  rememberExpiration: 604800

shuaicj.security.jwt.secret: otherpeopledontknowit

